- name: Create All RoboShop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - {name: "param.dev.catalogue.MONGO_ENDPOINT", value: "dev-mongodb.rajashekar.online"}
        - {name: "param.dev.user.MONGO", value: "true"}
        - {name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.rajashekar.online:8080/"}
        - {name: "param.dev.frontend.USER_URL", value: "http://dev-user.rajashekar.online:8080/"}
        - {name: "param.dev.frontend.CART_URL", value: "http://dev-cart.rajashekar.online:8080/"}
        - {name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.rajashekar.online:8080/"}
        - {name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.rajashekar.online:8080/"}